<CreateTab>
    ScrollView:
        do_scroll_x: False
        do_scroll_y: True

        MDGridLayout:
            cols: 1
            spacing: "12dp"
            padding: "12dp"
            adaptive_height: True

            RidersAdmin:
                size_hint: 1, None
                height: '600dp'

            ContestsAdmin:
                size_hint: 1, None
                height: '600dp'

