
<Check@MDCheckbox>:
    group: 'group'
    size_hint: None, None
    size: dp(48), dp(48)

<ScoreSheet>:
    orientation: 'vertical'
    MDBoxLayout:
        id: water
        size_hint: 1, .15
        spacing: '8dp'

    MDBoxLayout:
        id: scorecard

<JudgeTab>:
    MDBoxLayout:
        orientation: 'vertical'
        spacing: '12dp'
        padding: '8dp'

        ScoreSheet:






















